@PoetryLovers_HostAddress = http://localhost:5113

GET {{PoetryLovers_HostAddress}}/random
Accept: application/json

###

GET {{PoetryLovers_HostAddress}}/byTitle/darkness
Accept: application/json

###

GET {{PoetryLovers_HostAddress}}/byAuthor/dickinson/3
Accept: application/json

###
